* Data Ethics Literature Review

This is research project to survey academic literature surrounding ethics in data and data science.

* Goals

Goals of this research project include:

 - production of a website to display this collection
 - production of a course syllabus

* Structure of this Repository

This is an [[https://github.com/org-roam][org-roam]] [[https://en.wikipedia.org/wiki/Zettelkasten][Zettelkasten]], or a graph of interconnected notes representing our knowledge graph. It uses [[https://github.com/rasendubi/uniorg/tree/master/examples/org-braindump][org-braindump]] for making a website out its plain text files.

~/public/~: contains notes for each source. A source can be an article, web page, blog post, book, or similar source. Each source has a single file which contains notes and metadata for that source. Each file is an org-roam / [[https://orgmode.org/][org-mode]] file, named according to its bibliography key, as defined in ~bibliography.bib~.
~/papers~: contains PDFs of papers themselves, if available. Each paper should be named according to its bibliographic key. These may be withheld from the Git repository, for the moment.
~bibliography.bib~: a BibLaTeX file containing the bibliography.
~index.org~: the starting-point for the website.
~/src/~: contains next.js templates and source for building the website

* Specification

This may change soon, with issue #1. But for the moment:

Everything is a note. Notes can be:
 - Literature notes, tagged with ~lit~. These are books, articles, websites, or other textual sources. They are named according to their bibtex key.
   + Each has a top-level heading containing bibliographic metadata
 - Concept notes. These are atomic ideas.
 - Course / syllabus notes, tagged with ~course~.
   + Each has a top-level heading containing metadata about the course.
   + May contain links to literature that appears on the syllabus.
